CREATE DATABASE QLY_CONGCAFFE;
GO

USE QLY_CONGCAFFE;
GO
-- QUẢN LÝ BÁN HÀNG 

-- BẢNG NHÂN VIÊN 
CREATE TABLE NHANVIEN
(
    MaNV CHAR(10) CONSTRAINT PK_NHANVIEN PRIMARY KEY 
    CONSTRAINT CK_MANV_NHANVIEN CHECK (LEN(MaNV) BETWEEN 2 AND 10),
    TenNV NVARCHAR(50) NOT NULL,
    GioiTinh NVARCHAR(3) NOT NULL CONSTRAINT CK_GTNV CHECK (GioiTinh IN (N'Nam', N'Nữ')),
    NgaySinhNV DATETIME NOT NULL CONSTRAINT CK_NGAYSINH CHECK (NgaySinhNV < GETDATE()),
    STK CHAR(20) NOT NULL UNIQUE,
    SDTNV CHAR(10) UNIQUE 
    CONSTRAINT CK_SDTNV CHECK (SDTNV NOT LIKE '%[^0-9]%')
);
GO

-- BẢNG KHÁCH HÀNG 
CREATE TABLE KHACHHANG 
(
    MaKH CHAR(10) CONSTRAINT PK_KHACHHANG PRIMARY KEY 
    CONSTRAINT CK_MaKH_KHACHHANG CHECK (LEN(MaKH)=10),
    TenKH NVARCHAR(100) NOT NULL,
    NgaySinhKH DATE NOT NULL CHECK (NgaySinhKH < GETDATE()),
    DiaChiKH NVARCHAR(100) NOT NULL,
    SDTKH VARCHAR(10) CHECK (SDTKH NOT LIKE '%[^0-9]%') 
);
GO

-- BẢNG VỊ TRÍ 
CREATE TABLE VITRI
(
    MSBan CHAR(10) CONSTRAINT PK_BAN_VITRI PRIMARY KEY 
    CONSTRAINT CK_MSBAN_BAN CHECK (LEN(MSBAN)<=10),
    KVBan NVARCHAR(10) NOT NULL CONSTRAINT CK_KVB CHECK (LEN(KVBAN)<=10),
    TrangThai NVARCHAR(10) NOT NULL CONSTRAINT CK_TT CHECK (LEN(TRANGTHAI)<=10)
);
GO

-- BẢNG LOẠI SẢN PHẨM 
CREATE TABLE LOAISANPHAM
(
    MaLSP CHAR(10) CONSTRAINT PK_MaLSP_LOAISANPHAM PRIMARY KEY 
    CONSTRAINT CK_MALSP CHECK (LEN(MaLSP)<=10),
    TenLSP NVARCHAR(50) NOT NULL
);
GO

-- BẢNG SẢN PHẨM 
CREATE TABLE SANPHAM 
(
    MaSP CHAR(10) CONSTRAINT PK_MaSP_SANPHAM PRIMARY KEY 
    CONSTRAINT CK_MASP CHECK (LEN(MaSP)<=10),
    TenSP NVARCHAR(30) NOT NULL,
    GiaSP DECIMAL(10,2) NOT NULL CONSTRAINT CK_GIA CHECK (GiaSP>=0),
    MaLSP CHAR(10),
    CONSTRAINT FK_SP_LSP FOREIGN KEY (MaLSP) REFERENCES LOAISANPHAM(MaLSP) 
);
GO

-- BẢNG HÓA ĐƠN BÁN 
CREATE TABLE HOADON_BAN
(
    MaBILL CHAR(10) CONSTRAINT PK_HOADON PRIMARY KEY 
    CONSTRAINT CK_MABILL CHECK (LEN(MaBILL)<=10),
    TongTien DECIMAL(10,2) NOT NULL 
    CONSTRAINT CK_TONG_HDB CHECK (TongTien>=0),
    PTThanhToan NVARCHAR(50) NOT NULL,
    TGBAN DATETIME NOT NULL CONSTRAINT CK_TGBAN CHECK (TGBAN<=GETDATE()),
    MaKH CHAR(10), -- Đổi thành 11 cho khớp bảng KHACHHANG
    MaNV CHAR(10),
    MSBAN CHAR(10),
    -- Bổ sung các Khóa ngoại (Foreign Keys)
    CONSTRAINT FK_HDB_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT FK_HDB_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_HDB_VT FOREIGN KEY (MSBAN) REFERENCES VITRI(MSBan)
);
GO

-- BẢNG CHI TIẾT HÓA ĐƠN BÁN 
CREATE TABLE CTHD_BAN
(
    MaBILL CHAR(10),
    MaSP CHAR(10), 
    SoLuong INT NOT NULL CONSTRAINT CK_SOLUONG CHECK (SoLuong>0),
    GiaBan MONEY NOT NULL, -- Bổ sung giá bán để tính thành tiền
    ThanhTien AS (SoLuong * GiaBan),
    
    CONSTRAINT PK_CTHD PRIMARY KEY (MaBILL, MaSP),
    CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaBILL) REFERENCES HOADON_BAN(MaBILL), -- Trỏ đúng bảng HOADON_BAN
    CONSTRAINT FK_CTHD_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);
GO


--===============================================
-- QUẢN LÝ NHẬP KHO 
-- BẢNG NHÀ CUNG CẤP (NCC)
CREATE TABLE NCC
(
    MaNCC CHAR(6) CONSTRAINT PK_NCC PRIMARY KEY,
    TenNCC NVARCHAR(100) NOT NULL,
    DiaChiNCC NVARCHAR(150) NOT NULL,
    SDTNCC VARCHAR(10) NOT NULL CONSTRAINT UQ_SDTNCC UNIQUE 
    CONSTRAINT CK_SDTNCC CHECK (SDTNCC NOT LIKE '%[^0-9]%')
);
GO

-- BẢNG NGUYÊN VẬT LIỆU (NVL)
CREATE TABLE NVL
(
    MaNVL CHAR(10) CONSTRAINT PK_NVL PRIMARY KEY,
    TenNVL NVARCHAR(100) NOT NULL,
    DVT NVARCHAR(10) NOT NULL,
    DonGia DECIMAL(10,2) NOT NULL CONSTRAINT CK_DonGia_NVL CHECK (DonGia >= 0)
);
GO

-- BẢNG HÓA ĐƠN NHẬP (HOADON_NHAP)
CREATE TABLE HOADON_NHAP
(
    MaHD_NH CHAR(10) CONSTRAINT PK_HOADON_NHAP PRIMARY KEY,
    MaNV CHAR(10), 
    MaNCC CHAR(6), 
    NgayLap DATETIME NOT NULL CONSTRAINT CK_NgayLap_HDN CHECK (NgayLap <= GETDATE()),
    PTThanhToan CHAR(10) NOT NULL,
    TongTien DECIMAL(18,2) NOT NULL CONSTRAINT CK_TongTien_HDN CHECK (TongTien >= 0),
    ThueVAT DECIMAL(5,2) DEFAULT 0.1 CONSTRAINT CK_ThueVAT_HDN CHECK (ThueVAT >= 0),
    
    -- Ràng buộc khóa ngoại
    CONSTRAINT FK_HDN_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    CONSTRAINT FK_HDN_NCC FOREIGN KEY (MaNCC) REFERENCES NCC(MaNCC)
);
GO

-- BẢNG CHI TIẾT HÓA ĐƠN NHẬP (CTHD_NHAP)
CREATE TABLE CTHD_NHAP
(
    MaHD_NH CHAR(10),
    MaNVL CHAR(10),
    SoLuong INT NOT NULL CONSTRAINT CK_SoLuong_CTHDN CHECK (SoLuong > 0),
    ThanhTien DECIMAL(18,2) NOT NULL CONSTRAINT CK_ThanhTien_CTHDN CHECK (ThanhTien >= 0),
    HSD DATETIME NOT NULL,
    -- Ràng buộc khóa chính 
    CONSTRAINT PK_CTHD_NHAP PRIMARY KEY (MaHD_NH, MaNVL),
    -- Ràng buộc khóa ngoại
    CONSTRAINT FK_CTHDN_HOADON_NHAP FOREIGN KEY (MaHD_NH) REFERENCES HOADON_NHAP(MaHD_NH),
    CONSTRAINT FK_CTHDN_NVL FOREIGN KEY (MaNVL) REFERENCES NVL(MaNVL)
);
GO



USE QLY_CONGCAFFE;
GO

-- ==============================================
-- 1. SỬA BẢNG CTHD_NHAP
-- ==============================================
-- Bỏ ràng buộc CHECK của cột ThanhTien cũ
ALTER TABLE CTHD_NHAP DROP CONSTRAINT CK_ThanhTien_CTHDN;
GO

-- Xóa cột ThanhTien cũ
ALTER TABLE CTHD_NHAP DROP COLUMN ThanhTien;
GO

-- Thêm cột DonGiaNVL
ALTER TABLE CTHD_NHAP ADD DonGiaNVL DECIMAL(18,2) NOT NULL DEFAULT 0;
GO

-- Thêm lại cột ThanhTien dạng tự động tính (Computed Column)
ALTER TABLE CTHD_NHAP ADD ThanhTien AS (SoLuong * DonGiaNVL);
GO

-- ==============================================
-- 2. SỬA BẢNG CTHD_BAN
-- ==============================================
-- Xóa cột ThanhTien (vì nó đang phụ thuộc vào cột GiaBan cũ)
ALTER TABLE CTHD_BAN DROP COLUMN ThanhTien;
GO

-- Đổi tên cột GiaBan thành DonGiaSP
EXEC sp_rename 'CTHD_BAN.GiaBan', 'DonGiaSP', 'COLUMN';
GO

-- Đổi kiểu dữ liệu của DonGiaSP sang DECIMAL(18,2)
ALTER TABLE CTHD_BAN ALTER COLUMN DonGiaSP DECIMAL(18,2) NOT NULL;
GO

-- Thêm lại cột ThanhTien dạng tự động tính từ DonGiaSP
ALTER TABLE CTHD_BAN ADD ThanhTien AS (SoLuong * DonGiaSP);
GO


ALTER TABLE NVL
DROP CONSTRAINT CK_DonGia_NVL;
ALTER TABLE NVL
DROP COLUMN DonGia;

DELETE FROM HOADON_NHAP
SELECT * FROM HOADON_NHAP

SELECT * FROM HOADON_BAN

SELECT * FROM SANPHAM

SELECT * FROM NVL

SELECT * FROM CTHD_NHAP
