USE QLY_CONGCAFFE;
GO

-- 1. Mở rộng độ dài cột trước để không bị lỗi "Truncated"
ALTER TABLE KHACHHANG ALTER COLUMN SDTKH NVARCHAR(50);
ALTER TABLE KHACHHANG ALTER COLUMN DiaChiKH NVARCHAR(MAX);
GO

-- 2. Chỉ thực hiện giải mã NẾU cột _VARBINARY tồn tại
IF COL_LENGTH('KHACHHANG', 'SDTKH_VARBINARY') IS NOT NULL 
   OR COL_LENGTH('KHACHHANG', 'DiaChiKH_VARBINARY') IS NOT NULL
BEGIN
    -- Mở khóa
    IF EXISTS (SELECT 1 FROM sys.symmetric_keys WHERE name = 'SK_KHACHHANG')
    BEGIN
        OPEN SYMMETRIC KEY SK_KHACHHANG DECRYPTION BY CERTIFICATE Cert_KHACHHANG;
        
        -- Cập nhật dữ liệu từ cột mã hóa về cột thuần túy
        IF COL_LENGTH('KHACHHANG', 'SDTKH_VARBINARY') IS NOT NULL
            UPDATE KHACHHANG SET SDTKH = CONVERT(NVARCHAR(50), DecryptByKey(SDTKH_VARBINARY));

        IF COL_LENGTH('KHACHHANG', 'DiaChiKH_VARBINARY') IS NOT NULL
            UPDATE KHACHHANG SET DiaChiKH = CONVERT(NVARCHAR(MAX), DecryptByKey(DiaChiKH_VARBINARY));
            
        CLOSE SYMMETRIC KEY SK_KHACHHANG;
    END
END
GO

-- 3. Xóa các cột gây lỗi "image_f099c4.png" nếu chúng còn tồn tại
IF COL_LENGTH('KHACHHANG', 'SDTKH_VARBINARY') IS NOT NULL
    ALTER TABLE KHACHHANG DROP COLUMN SDTKH_VARBINARY;

IF COL_LENGTH('KHACHHANG', 'DiaChiKH_VARBINARY') IS NOT NULL
    ALTER TABLE KHACHHANG DROP COLUMN DiaChiKH_VARBINARY;
GO

-- 4. Kiểm tra lại dữ liệu cuối cùng
SELECT MaKH, TenKH, SDTKH, DiaChiKH FROM KHACHHANG;

UPDATE KHACHHANG SET SDTKH = NULL, DiaChiKH = NULL;