USE [QLY_CONGCAFFE]
GO
/****** Object:  Table [dbo].[CTHD_BAN]    Script Date: 5/3/2026 3:19:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTHD_BAN](
	[MaBILL] [char](10) NOT NULL,
	[MaSP] [char](10) NOT NULL,
	[SoLuong] [int] NOT NULL,
	[DonGiaSP] [decimal](18, 2) NOT NULL,
	[ThanhTien]  AS ([SoLuong]*[DonGiaSP]),
 CONSTRAINT [PK_CTHD] PRIMARY KEY CLUSTERED 
(
	[MaBILL] ASC,
	[MaSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTHD_NHAP]    Script Date: 5/3/2026 3:19:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTHD_NHAP](
	[MaHD_NH] [char](10) NOT NULL,
	[MaNVL] [char](10) NOT NULL,
	[SoLuong] [int] NOT NULL,
	[HSD] [datetime] NOT NULL,
	[DonGiaNVL] [decimal](18, 2) NOT NULL,
	[ThanhTien]  AS ([SoLuong]*[DonGiaNVL]),
 CONSTRAINT [PK_CTHD_NHAP] PRIMARY KEY CLUSTERED 
(
	[MaHD_NH] ASC,
	[MaNVL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON_BAN]    Script Date: 5/3/2026 3:19:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON_BAN](
	[MaBILL] [char](10) NOT NULL,
	[TongTien] [decimal](10, 2) NOT NULL,
	[PTThanhToan] [nvarchar](50) NOT NULL,
	[TGBAN] [datetime] NOT NULL,
	[MaKH] [char](10) NULL,
	[MaNV] [char](10) NULL,
	[MSBAN] [char](10) NULL,
 CONSTRAINT [PK_HOADON] PRIMARY KEY CLUSTERED 
(
	[MaBILL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON_NHAP]    Script Date: 5/3/2026 3:19:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON_NHAP](
	[MaHD_NH] [char](10) NOT NULL,
	[MaNV] [char](10) NULL,
	[MaNCC] [char](6) NULL,
	[NgayLap] [datetime] NOT NULL,
	[PTThanhToan] [char](10) NOT NULL,
	[TongTien] [decimal](18, 2) NOT NULL,
	[ThueVAT] [decimal](5, 2) NULL,
 CONSTRAINT [PK_HOADON_NHAP] PRIMARY KEY CLUSTERED 
(
	[MaHD_NH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 5/3/2026 3:19:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MaKH] [char](10) NOT NULL,
	[TenKH] [nvarchar](100) NOT NULL,
	[NgaySinhKH] [date] NOT NULL,
	[SDTKH] [varbinary](max) NULL,
	[DiaChiKH] [varbinary](max) NULL,
 CONSTRAINT [PK_KHACHHANG] PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAISANPHAM]    Script Date: 5/3/2026 3:19:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAISANPHAM](
	[MaLSP] [char](10) NOT NULL,
	[TenLSP] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MaLSP_LOAISANPHAM] PRIMARY KEY CLUSTERED 
(
	[MaLSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NCC]    Script Date: 5/3/2026 3:19:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NCC](
	[MaNCC] [char](6) NOT NULL,
	[TenNCC] [nvarchar](100) NOT NULL,
	[DiaChiNCC] [nvarchar](150) NOT NULL,
	[SDTNCC] [varchar](10) NOT NULL,
 CONSTRAINT [PK_NCC] PRIMARY KEY CLUSTERED 
(
	[MaNCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_SDTNCC] UNIQUE NONCLUSTERED 
(
	[SDTNCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 5/3/2026 3:19:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MaNV] [char](10) NOT NULL,
	[TenNV] [nvarchar](50) NOT NULL,
	[GioiTinh] [nvarchar](3) NOT NULL,
	[NgaySinhNV] [datetime] NOT NULL,
	[STK] [char](20) NOT NULL,
	[SDTNV] [char](10) NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MaNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[STK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SDTNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NVL]    Script Date: 5/3/2026 3:19:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NVL](
	[MaNVL] [char](10) NOT NULL,
	[TenNVL] [nvarchar](100) NOT NULL,
	[DVT] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_NVL] PRIMARY KEY CLUSTERED 
(
	[MaNVL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SANPHAM]    Script Date: 5/3/2026 3:19:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SANPHAM](
	[MaSP] [char](10) NOT NULL,
	[TenSP] [nvarchar](30) NOT NULL,
	[MaLSP] [char](10) NULL,
	[GiaSP] [decimal](18, 2) NULL,
 CONSTRAINT [PK_MaSP_SANPHAM] PRIMARY KEY CLUSTERED 
(
	[MaSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VITRI]    Script Date: 5/3/2026 3:19:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VITRI](
	[MSBan] [char](10) NOT NULL,
	[KVBan] [nvarchar](10) NOT NULL,
	[TrangThai] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_BAN_VITRI] PRIMARY KEY CLUSTERED 
(
	[MSBan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTHD_NHAP] ADD  DEFAULT ((0)) FOR [DonGiaNVL]
GO
ALTER TABLE [dbo].[HOADON_NHAP] ADD  DEFAULT ((0.1)) FOR [ThueVAT]
GO
ALTER TABLE [dbo].[CTHD_BAN]  WITH CHECK ADD  CONSTRAINT [FK_CTHD_HD] FOREIGN KEY([MaBILL])
REFERENCES [dbo].[HOADON_BAN] ([MaBILL])
GO
ALTER TABLE [dbo].[CTHD_BAN] CHECK CONSTRAINT [FK_CTHD_HD]
GO
ALTER TABLE [dbo].[CTHD_BAN]  WITH CHECK ADD  CONSTRAINT [FK_CTHD_SP] FOREIGN KEY([MaSP])
REFERENCES [dbo].[SANPHAM] ([MaSP])
GO
ALTER TABLE [dbo].[CTHD_BAN] CHECK CONSTRAINT [FK_CTHD_SP]
GO
ALTER TABLE [dbo].[CTHD_NHAP]  WITH CHECK ADD  CONSTRAINT [FK_CTHDN_HOADON_NHAP] FOREIGN KEY([MaHD_NH])
REFERENCES [dbo].[HOADON_NHAP] ([MaHD_NH])
GO
ALTER TABLE [dbo].[CTHD_NHAP] CHECK CONSTRAINT [FK_CTHDN_HOADON_NHAP]
GO
ALTER TABLE [dbo].[CTHD_NHAP]  WITH CHECK ADD  CONSTRAINT [FK_CTHDN_NVL] FOREIGN KEY([MaNVL])
REFERENCES [dbo].[NVL] ([MaNVL])
GO
ALTER TABLE [dbo].[CTHD_NHAP] CHECK CONSTRAINT [FK_CTHDN_NVL]
GO
ALTER TABLE [dbo].[HOADON_BAN]  WITH CHECK ADD  CONSTRAINT [FK_HDB_KH] FOREIGN KEY([MaKH])
REFERENCES [dbo].[KHACHHANG] ([MaKH])
GO
ALTER TABLE [dbo].[HOADON_BAN] CHECK CONSTRAINT [FK_HDB_KH]
GO
ALTER TABLE [dbo].[HOADON_BAN]  WITH CHECK ADD  CONSTRAINT [FK_HDB_NV] FOREIGN KEY([MaNV])
REFERENCES [dbo].[NHANVIEN] ([MaNV])
GO
ALTER TABLE [dbo].[HOADON_BAN] CHECK CONSTRAINT [FK_HDB_NV]
GO
ALTER TABLE [dbo].[HOADON_BAN]  WITH CHECK ADD  CONSTRAINT [FK_HDB_VT] FOREIGN KEY([MSBAN])
REFERENCES [dbo].[VITRI] ([MSBan])
GO
ALTER TABLE [dbo].[HOADON_BAN] CHECK CONSTRAINT [FK_HDB_VT]
GO
ALTER TABLE [dbo].[HOADON_NHAP]  WITH CHECK ADD  CONSTRAINT [FK_HDN_NCC] FOREIGN KEY([MaNCC])
REFERENCES [dbo].[NCC] ([MaNCC])
GO
ALTER TABLE [dbo].[HOADON_NHAP] CHECK CONSTRAINT [FK_HDN_NCC]
GO
ALTER TABLE [dbo].[HOADON_NHAP]  WITH CHECK ADD  CONSTRAINT [FK_HDN_NHANVIEN] FOREIGN KEY([MaNV])
REFERENCES [dbo].[NHANVIEN] ([MaNV])
GO
ALTER TABLE [dbo].[HOADON_NHAP] CHECK CONSTRAINT [FK_HDN_NHANVIEN]
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [FK_SP_LSP] FOREIGN KEY([MaLSP])
REFERENCES [dbo].[LOAISANPHAM] ([MaLSP])
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [FK_SP_LSP]
GO
ALTER TABLE [dbo].[CTHD_BAN]  WITH CHECK ADD  CONSTRAINT [CK_SOLUONG] CHECK  (([SoLuong]>(0)))
GO
ALTER TABLE [dbo].[CTHD_BAN] CHECK CONSTRAINT [CK_SOLUONG]
GO
ALTER TABLE [dbo].[CTHD_NHAP]  WITH CHECK ADD  CONSTRAINT [CK_SoLuong_CTHDN] CHECK  (([SoLuong]>(0)))
GO
ALTER TABLE [dbo].[CTHD_NHAP] CHECK CONSTRAINT [CK_SoLuong_CTHDN]
GO
ALTER TABLE [dbo].[HOADON_BAN]  WITH CHECK ADD  CONSTRAINT [CK_MABILL] CHECK  ((len([MaBILL])<=(10)))
GO
ALTER TABLE [dbo].[HOADON_BAN] CHECK CONSTRAINT [CK_MABILL]
GO
ALTER TABLE [dbo].[HOADON_BAN]  WITH CHECK ADD  CONSTRAINT [CK_TGBAN] CHECK  (([TGBAN]<=getdate()))
GO
ALTER TABLE [dbo].[HOADON_BAN] CHECK CONSTRAINT [CK_TGBAN]
GO
ALTER TABLE [dbo].[HOADON_BAN]  WITH CHECK ADD  CONSTRAINT [CK_TONG_HDB] CHECK  (([TongTien]>=(0)))
GO
ALTER TABLE [dbo].[HOADON_BAN] CHECK CONSTRAINT [CK_TONG_HDB]
GO
ALTER TABLE [dbo].[HOADON_NHAP]  WITH CHECK ADD  CONSTRAINT [CK_NgayLap_HDN] CHECK  (([NgayLap]<=getdate()))
GO
ALTER TABLE [dbo].[HOADON_NHAP] CHECK CONSTRAINT [CK_NgayLap_HDN]
GO
ALTER TABLE [dbo].[HOADON_NHAP]  WITH CHECK ADD  CONSTRAINT [CK_ThueVAT_HDN] CHECK  (([ThueVAT]>=(0)))
GO
ALTER TABLE [dbo].[HOADON_NHAP] CHECK CONSTRAINT [CK_ThueVAT_HDN]
GO
ALTER TABLE [dbo].[HOADON_NHAP]  WITH CHECK ADD  CONSTRAINT [CK_TongTien_HDN] CHECK  (([TongTien]>=(0)))
GO
ALTER TABLE [dbo].[HOADON_NHAP] CHECK CONSTRAINT [CK_TongTien_HDN]
GO
ALTER TABLE [dbo].[KHACHHANG]  WITH CHECK ADD CHECK  (([NgaySinhKH]<getdate()))
GO
ALTER TABLE [dbo].[KHACHHANG]  WITH CHECK ADD  CONSTRAINT [CK_MaKH_KHACHHANG] CHECK  ((len([MaKH])=(10)))
GO
ALTER TABLE [dbo].[KHACHHANG] CHECK CONSTRAINT [CK_MaKH_KHACHHANG]
GO
ALTER TABLE [dbo].[LOAISANPHAM]  WITH CHECK ADD  CONSTRAINT [CK_MALSP] CHECK  ((len([MaLSP])<=(10)))
GO
ALTER TABLE [dbo].[LOAISANPHAM] CHECK CONSTRAINT [CK_MALSP]
GO
ALTER TABLE [dbo].[NCC]  WITH CHECK ADD  CONSTRAINT [CK_SDTNCC] CHECK  ((NOT [SDTNCC] like '%[^0-9]%'))
GO
ALTER TABLE [dbo].[NCC] CHECK CONSTRAINT [CK_SDTNCC]
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [CK_GTNV] CHECK  (([GioiTinh]=N'Nữ' OR [GioiTinh]=N'Nam'))
GO
ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [CK_GTNV]
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [CK_MANV_NHANVIEN] CHECK  ((len([MaNV])>=(2) AND len([MaNV])<=(10)))
GO
ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [CK_MANV_NHANVIEN]
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [CK_NGAYSINH] CHECK  (([NgaySinhNV]<getdate()))
GO
ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [CK_NGAYSINH]
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD  CONSTRAINT [CK_SDTNV] CHECK  ((NOT [SDTNV] like '%[^0-9]%'))
GO
ALTER TABLE [dbo].[NHANVIEN] CHECK CONSTRAINT [CK_SDTNV]
GO
ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [CK_MASP] CHECK  ((len([MaSP])<=(10)))
GO
ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [CK_MASP]
GO
ALTER TABLE [dbo].[VITRI]  WITH CHECK ADD  CONSTRAINT [CK_KVB] CHECK  ((len([KVBAN])<=(10)))
GO
ALTER TABLE [dbo].[VITRI] CHECK CONSTRAINT [CK_KVB]
GO
ALTER TABLE [dbo].[VITRI]  WITH CHECK ADD  CONSTRAINT [CK_MSBAN_BAN] CHECK  ((len([MSBAN])<=(10)))
GO
ALTER TABLE [dbo].[VITRI] CHECK CONSTRAINT [CK_MSBAN_BAN]
GO
ALTER TABLE [dbo].[VITRI]  WITH CHECK ADD  CONSTRAINT [CK_TT] CHECK  ((len([TRANGTHAI])<=(10)))
GO
ALTER TABLE [dbo].[VITRI] CHECK CONSTRAINT [CK_TT]
GO
